title: Lim Zheng Gang
logo: /images/photo_with_border.png
description: I specialize in building strong, analytical operations teams and creating a positive work environment. My expertise lies in helping companies achieve their goals by optimizing processes and reducing operational costs. I am passionate about nurturing individuals, solving problems through innovative methods, and finding motivation in witnessing personal and organizational growth. With a realistic and analytical perspective, I bridge the gap between operations and strategic objectives, offering valuable insights and solutions.
show_downloads: False
theme: jekyll-theme-minimal 
