title: Lim Zheng Gang
logo: /images/photo_with_border.png
description: Specializes in building strong, analytical operations teams and creating a positive work environment.
theme: jekyll-theme-minimal 
