title: Zheng Gang Lim
logo: /images/circular_bw_image.png
description: Dedicated to developing robust, analytical teams and fostering a constructive work atmosphere. My focus is on streamlining processes and cutting costs to help businesses reach their targets. I thrive on mentoring talent, employing creative problem-solving, and seeing growth on both personal and company levels. With a pragmatic and analytical approach, I connect day-to-day operations with strategic goals, delivering impactful insights and solutions.
show_downloads: False
theme: jekyll-theme-minimal 
